### ISSUE TITLE
permission denied if no docker user

### ISSUE THREAD

**Issue by GeniusWiki** [rmohr/docker-activemq#22]
I have setup docker in Ubuntu 16.04 with offical setup steps. 

When run you docker image, it failed to start because it cannot create /activemq/data/kahadb directory.  After I manually give 777 permission on /activemq/data (root:root), it can success start and create kahadb directory with 999:docker as user:group.  

Here is my docker-compose config:

```
    activemq:
        image: rmohr/activemq:latest
        environment:
            ACTIVEMQ_DATA: "/var/lib/activemq/data"
        volumes:
            - ./data/activemq/data:/var/lib/activemq/data
```
